w-a-r-m-inventory-system/Food-Pantry-Inventory

Contributors.md

modified to show names on consecutive lines

Updated with my name and other modification

---

docs/source/UML Diagrams.rst

Added links to the UML source files and deleted the debris after the project-specific information.

Added references to UML diagram source files to the UML Diagram rst document.

---

docs/Git Guidelines.rst
docs/source/UML Diagrams.rst
docs/source/UML/PlantUML Version.puml
requirements.txt

Included in this pull request is a document of guidelines for using git to manage changes.  Also included are changes to have Sphinx automatically generate the UML diagrams and incorporate the diagrams in the html output.

Add Git Guidelines and Improve UML Management

---

docs/Git Guidelines.rst

Improved guidelines in a number of minor ways.
- Indented  command literals so numbering is no longer restarted.
- Added clarifications here and there.
- Finished the instructions for one step that was incomplete.

Improve Git Guidelines document

---

docs/Git Guidelines.rst

Added **Django** to the required libraries to be installed to work on this project.

Add Django to Git Guidelines.rst file

---

docs/Git Guidelines.rst
requirements.txt

Added more details to the Git Guidelines document and updated requirements .txt accordingly.

Added more support for Sphinx/PlantUML integration.

---

docs/DevDocs
docs/DevDocs.md

Updated Dango reference to the current version (2.1) and changed doc to be a markdown document since it started out with md syntax.

Updated reference to current Django web site.

---

FPIDjango/settings.py
FPIDjango/urls.py
docs/Django Guidelines.rst
docs/PostgreSQL Guidelines.rst
fpiweb/admin.py
fpiweb/apps.py
fpiweb/models.py
fpiweb/tests.py
fpiweb/urls.py
fpiweb/views.py

- Added app called fpiweb.
- Added definition for postgreSQL db called WARM.
- Ready to define tables.
Note - for now the database settings are hard coded into FPDjango/settings.py file - **including the password** for the PostgreSQL administrator

Added a fpiweb application under Django and configured PostgreSQL.

---

fpiweb/models.py

- Somehow the key names either didn't get changed or reverted to their
old names.  This commit fixes them.

Fix key names in model so they match migration.

---

fpiweb/templates/fpiweb/login.html
fpiweb/views.py

changes to account for changes that Travis made to urls.py

fixes to urls to accomodate fpiweb namespace

---

docs/source/DevDocs/Django.rst

wrote up a bit of documentation re: using Django's auth system

Using login required mixin

---

FPIDjango/settings.py
data/tsv2json.py
fpiweb/fixtures/BoxType.json
fpiweb/forms.py
fpiweb/models.py

code to provide drop-downs for as many inputs as possible in the add inventory screen.

created select elements for bin, row, and tier

---

FPIDjango/settings.py
fpiweb/views.py

copy the LOG_DIR and LOGGING from settings.py into your versions of settings.py

configured logging.

---

docs/source/DevDocs/DevDocs.rst
docs/source/DevDocs/Django Guidelines.rst

- Updated what version of Django being used to 2.2.1 in *Developer Documentation*
- Updated `Environment variables` property in the *Create New Run Configuration* in *Django Guidelines*
- Added `Parameters` property to *Create New Run Configuration* in *Django Guidelines*
- Rewrote the steps in *Tailor Django Access* in *Django Guidelines*

Updated Documentation

---

fpiweb/templates/fpiweb/base.html

This change should make developing with local bootstrap work.

Committing local bootstrap fix

---

fpiweb/tests.py
pytest.ini

Making it easier to run vanilla pytest

Tests updates

---

fpiweb/admin.py
fpiweb/forms.py
fpiweb/models.py
fpiweb/static/fpiweb/style.css
fpiweb/support/BoxActivity.py
fpiweb/templates/fpiweb/base.html
fpiweb/templates/fpiweb/manual_menu.html
fpiweb/templates/fpiweb/manual_move_box.html
fpiweb/tests/test_models.py
fpiweb/tests/test_views.py
fpiweb/urls.py
fpiweb/views.py

Note: `SomeModelClass.objects.get` will either return an instance of `SomeModelClass` or raise an exception.  I found a spot in BoxActivity where you were testing whether `None` was returned.  `objects.get` doesn't return `None`

wrapped up work on manual move functionality

---

.coveragerc
fpiweb/tests/test_support_activity.py

- Ignore .venv virtual environments for coverage
- Typo caused one test case to be skipped

Minor test updates

---

fpiweb/admin.py
fpiweb/models.py

I left out the migration files so you'll need to run `makemigrations` to generate them.  Leaving them out means should minimize conflicts in migrating your database.  Once you've migrated your database check in the migration files that you've created as the official copies.

added name to Pallet and a couple other data model changes

---

docs/source/DevDocs/Box Management.rst
fpiweb/support/BoxActivity.py
fpiweb/support/BoxManagement.py
fpiweb/tests/test_support_activity.py

- Added box management support documentation (Box Management.rst)
- Added minimal box management code (BoxManagement.py)
-- Code has the public api calls, parameters and returns.
-- Code is not functional at this time
-- Does not update the database
-- Always assumes call was valid

feat: Box management support - first pass

---

docs/source/DevDocs/Box Management.rst
fpiweb/qr_code_utilities.py
fpiweb/support/BoxManagement.py

- Documents box management and implements stubs to call.
- Stubs are not functional; box records are not updated.

feat: Box management documentation and stubs

---

.github/workflows/run-tests.yaml

Updated the Actions workflow to run test against Python 3.7 rather than latest (currently 3.8).

We're planning to roll out with Python 3.7

---

README.md

This goes along with the setup for ReadTheDocs #151

Add documentation badge and fix a few typos.

---

fpiweb/models.py
fpiweb/support/BoxActivity.py

- Fixed some edge cases in Box Activity
- Improve __str__ for Activity Record

fix: BoxActivity fixes and model improvements

---

fpiweb/forms.py
fpiweb/qr_code_utilities.py
fpiweb/support/BoxManagement.py
fpiweb/templates/fpiweb/base.html
fpiweb/templates/fpiweb/manual_check_in_box.html
fpiweb/templates/fpiweb/manual_ind_box_menu.html
fpiweb/templates/fpiweb/manual_pallet_menu.html
fpiweb/views.py
run_inv

Apply various UI tweaks and bug fixes to create a new stable base.

fix: Various UI tweaks to make the system run correctly.

---

docs/source/Developer Documentation.rst
docs/source/Individual Box Instructions.rst
docs/source/Other Tools.rst
docs/source/Overview.rst
docs/source/Pallet Instructions.rst
docs/source/Restructured Text Examples.rst
docs/source/User Documentation.rst
docs/source/conf.py
docs/source/index.rst

- Added Restructured Text Examples.rst of commonly used rST markup.
- Broke the User Documentation into four documents for easier editing.
-- By making it four documents, multiple people can edit separate documents
while minimizing the number of git conflicts.
-- A side effect of this split is that each document will be shown on a
separate web page.

docs: Added rST sample document and other documentation tweaks.

---

docs/source/Developer Documentation.rst
docs/source/Individual Box Instructions.rst
docs/source/Other Tools.rst
docs/source/Overview.rst
docs/source/Pallet Instructions.rst
docs/source/Restructured Text Examples.rst
docs/source/User Documentation.rst
docs/source/conf.py
docs/source/index.rst
fpiweb/forms.py
fpiweb/qr_code_utilities.py
fpiweb/support/BoxManagement.py
fpiweb/templates/fpiweb/base.html
fpiweb/templates/fpiweb/manual_check_in_box.html
fpiweb/templates/fpiweb/manual_ind_box_menu.html
fpiweb/templates/fpiweb/manual_pallet_menu.html
fpiweb/views.py
run_inv

-  Added Restructured Text Examples.rst of commonly used rST markup.
-  Broke the User Documentation into four documents for easier editing.
-- By making it four documents, multiple people can edit separate documents
while minimizing the number of git conflicts.
-- A side effect of this split is that each document will be shown on a
separate web page.

 docs: Added rST sample document and other documentation tweaks.

---

pytest.ini

fix(Other): Fix pytest configuration so coverage is run again.

---

fpiweb/tests/test_views.py
fpiweb/views.py

Doesn't look like the dev branch has changed since the last merge request

setting Pallet status to MOVE

---

docs/source/fpiweb.tests.rst
fpiweb/tests/test_func_ManualBoxManagement.py
fpiweb/tests/test_func_ManualPalletManagement.py
fpiweb/tests/utility.py

Contains 2 functional Selenium test suites. (1) for Manual Box Management pages. (2) for Move a pallet pages. Includes documentation for Manual Box Management pages. Does not include documentation for Move a pallet pages.

02 manual pallet management

---

fpiweb/constants.py
fpiweb/forms.py
fpiweb/models.py
fpiweb/views.py

Fixes issue #230 where a stack trace was shown rather than a polite invalid value message.
Closes 230

Box number validation

---

.github/workflows/run-tests.yaml

Add an additional parameter needed to support nginx or other web server.
Closes 262

ci(Other): Adjust Github workflow configuration file

---

fpiweb/forms.py
fpiweb/templates/fpiweb/loc_bin_delete.html
fpiweb/templates/fpiweb/loc_row_delete.html
fpiweb/templates/fpiweb/loc_row_edit.html
fpiweb/templates/fpiweb/loc_tier_delete.html
fpiweb/templates/fpiweb/manual_loc_table_edit.html
fpiweb/templates/fpiweb/manual_loc_table_list.html
fpiweb/views.py

Updated ManualLocTable Views- ManualLocTableCreateView, ManualLocTableListView, and ManualTableUpdateView. Fixed bug in ManualTableCreateView. In researching this bug found additional bugs I wrote in other CreateViews where I bypassed validation rules so I fixed that too. This should be running with the latest dev version and Python 3.8

08 manual location table

---

.github/workflows/run-tests.yaml
run_nginx.sh

- corrected a boo-boo in the github workflow file
- corrected a reference to a bad directory when attempting to
start nginx

fix(Code): Fixed bug in workflow yaml file and another in a script

---

FPIDjango/settings.py
fpiweb/forms.py
fpiweb/models.py
fpiweb/templates/fpiweb/box_type_maintenance_delete.html
fpiweb/templates/fpiweb/box_type_maintenance_edit.html
fpiweb/templates/fpiweb/box_type_maintenance_list.html
fpiweb/templates/fpiweb/box_type_maintence_delete.html
fpiweb/templates/fpiweb/system_maintenance.html
fpiweb/urls.py
fpiweb/views.py

Added BoxTypeMaintenceForm, BoxTypeMaintenanceListView, CreateView, UpdateView and DeleteView. Minor editing changes to ProductEaxmpleForm. Added success message to ProductExampleCreateView, UpdateView and DeleteView. Added:
INTERNAL_IPS = ['127.0.0.1',] to if DEBUG: statement in settings.py

11 box type maintenance

---

FPIDjango/settings.py
FPIDjango/urls.py
fpiweb/forms.py
fpiweb/fpiweb_views/PrintLabelView.py
fpiweb/password_validation.py
fpiweb/templates/fpiweb/change_password.html
fpiweb/templates/fpiweb/index.html
fpiweb/tests/test_forms.py
fpiweb/tests/test_func_UserManagement.py
fpiweb/tests/test_password_validation.py
fpiweb/tests/test_views.py
fpiweb/urls.py
fpiweb/views.py

switched login, logout, and change password to stock Django views.

176 allow user to change password
